import Head from 'next/head'
import { useSelector } from 'react-redux'
import Cart from '../components/Cart'
import Products from '../components/Products'


export default function Home() {
  const count = useSelector((state) => state.counter.value);


  return (
    <main className='bg-sec'>
      <Head>
        <title>MyShop|Next-redux App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Products />


      <div className='container py-3'>
        <h1>My Cart</h1><hr />
        <Cart />
      </div>

      <section className="py-0">
  
      </section>

    </main>
  )
}
